use championnat;

DROP TABLE IF EXISTS clubs;

CREATE TABLE clubs (
equipe_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(80) NOT NULL,
siege VARCHAR(80) NOT NULL
);

INSERT INTO clubs (nom, siege) VALUES 
('Inconnu', 'Inconnu'),
('AC Ajaccio', 'Ajaccio'),
('Amiens Sporting Club', 'Amiens'),
('Angers SCO','Angers'),
('AC Arles-Avignon','Arles'),
('AJ Auxerroise', 'Auxerre'),
('AS Aix-en-Provence', 'Aix-en-Provence'),
('AS Angoulême', 'Angoulême'),
('AS Béziers', 'Béziers'),
('AS Cannes', 'Cannes'),
('AS Monaco FC', 'Monaco'),
('AS Nancy-Lorraine', 'Nancy'),
('AS Saint-Étienne', 'Saint-Étienne'),
('AS Troyes et Savinienne', 'Troyes'),
('AS Troyes-Sainte-Savine', 'Troyes'),
('CO Roubaix-Tourcoing', 'Roubaix'),
('CS Sedan-Ardennes', 'Sedan'),
('CS Sedanais', 'Sedan'),
('Chamois Niortais FC', 'Niort'),
('Dijon FCO','Dijon'),
('ES Troyes AC', 'Troyes'),
('Évian TG FC','Évian'),
('Évian Thonon Gaillard FC','Évian'),
('En Avant Guingamp', 'Guingamp'),
('FC Brest Armorique', 'Brest'),
('FC Girondins de Bordeaux', 'Bordeaux'),
('FC Grenoble', 'Grenoble'),
('FC Gueugnon', 'Gueugnon'),
('FC Istres Ouest Provence', 'Istres'),
('FC Lorient Bretagne-Sud', 'Lorient'),
('FC Lorient Bretagne Sud', 'Lorient'),
('FC Martigues', 'Martigues'),
('FC Metz', 'Metz'),
('FC Mulhouse', 'Mulhouse'),
('FC Nancy', 'Nancy'),
('FC Nantes', 'Nantes'),
('FC Nantes-Atlantique', 'Nantes'),
('FC Rouen', 'Rouen'),
('FC Sochaux-Montbéliard', 'Montbéliard'),
('FC Sète', 'Sète'),
('FC Tours', 'Tours'),
('Gazélec FC Ajaccio','Ajaccio'),
('Grenoble Foot-38', 'Grenoble'),
('La Berrichonne Châteauroux', 'Châteauroux'),
('Le Havre AC FA', 'Le Havre'),
('Le Mans UC ’72', 'Le Mans'),
('Lille OSC', 'Lille'),
('Limoges FC', 'Limoges'),
('Lyon Olympique Universitaire', 'Lyon'),
('Montpellier La Paillade SC', 'Montpellier'),
('Montpellier-Hérault SC', 'Montpellier'),
('Nîmes Olympique', 'Nîmes'),
('OGC Nice', 'Nice'),
('OGC Nice Côte d’Azur', 'Nice'),
('Olympique Alésien', 'Alès'),
('Olympique Avignonnais', 'Avignon'),
('Olympique Lyonnais', 'Lyon'),
('Olympique de Marseille', 'Marseille'),
('Paris FC', 'Paris'),
('Paris Saint-Germain FC', 'Paris'),
('Paris St.Germain FC', 'Paris'),
('Racing Club Paris', 'Paris'),
('Racing Club Paris-Sedan', 'Sedan'),
('Racing Club Strasbourg', 'Strasbourg'),
('Racing Club Strasbourg-Pierrots', 'Strasbourg'),
('Racing Club de Paris', 'Paris'),
('Racing Club de Strasbourg', 'Strasbourg'),
('Racing Club de Strasbourg Alsace','Strasbourg'),
('Racing Club de Lens', 'Lens'),
('Red Star FC Saint-Ouen', 'Saint-Ouen'),
('Red Star Olympique Audonien', 'Saint-Ouen'),
('SC Bastia', 'Bastia'),
('SC Toulon', 'Toulon'),
('SCO Angers', 'Angers'),
('SEC Bastia', 'Bastia'),
('SO Montpellier', 'Montpellier'),
('SR Colmar', 'Colmar'),
('Stade Brestois', 'Brest'),
('Stade Brestois 29', 'Brest'),
('Stade Français FC Paris', 'Paris'),
('Stade Français Paris', 'Paris'),
('Stade Français Red Star Paris', 'Paris'),
('Stade Lavallois', 'Laval'),
('Stade Malherbe Caen', 'Caen'),
('Stade Rennais FC', 'Rennes'),
('Stade Rennais UC', 'Rennes'),
('Stade de Reims', 'Reims'),
('Toulouse FC', 'Toulouse'),
('Toulouse FC (ancien)', 'Toulouse'),
('Troyes AF', 'Troyes'),
('UA Sedan-Torcy', 'Sedan'),
('US Boulogne-sur-Mer', 'Boulogne-sur-Mer'),
('US Valenciennes', 'Valenciennes'),
('US Valenciennes-Anzin', 'Valenciennes'),
('Valenciennes FC', 'Valenciennes')
;
